
INSERT INTO m_escenalibro (
    codescena, desscena, flvigente, codusuarioauditoria, 
    fecreacionregistro, horacreacionregistro, 
    fecactualizacionregistro, horaactualizacionregistro
) VALUES 
('CRS01b', 'SCENE 1 - Show me how - Abi', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRS02b', 'SCENE 2 - Morning schmex - Abi', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRS03b', 'SCENE 3 - Please Lara, please - Abi', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRS04b', 'SCENE 4 - Die for her - Abi', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH01a', 'Hook 1 - Body Image 😳❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH02a', 'Hook 2 - Bike Chase 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH03a', 'Hook 3 - Pretty Mess 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH04a', 'Hook 4 - Full Control 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH05a', 'Hook 5 - Tie Up 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH06a', 'Hook 6 - Stalker Realization 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH07a', 'Hook 7 - First Time 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH08a', 'Hook 8 - Teach me 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH09a', 'Hook 9 - Mmc Virgin 😳🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH10a', 'Hook 10 - Alternative Virgin Reveal 😳🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH11a', 'Hook 11 - V3 Virgin Discovery 😳🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH12a', 'Hook 12 - Blood on hands 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH13a', 'Hook 13 - Hospital 😢❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH14a', 'Hook 14 - First Kiss ❤️💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH15a', 'Hook 15 - Rescue ❤️💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH16a', 'Hook 16 - Bad Date 😳❤️💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH17a', 'Hook 17 - No Boyfriends 😳💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH18a', 'Hook 18 - Stalker 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH19a', 'Hook 19 - Spicy hand necklace lesson 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH20a', 'Hook 20 - Office 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH21a', 'Hook 21 - Sex Club 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CRH22a', 'Hook 22 - Reward 🌶💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR01c', 'Hook 1 - Chapter 4 - Alondra: Video Format 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR02c', 'Hook 2 - Chapter 5 - Alondra: Video Format 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR03c', 'Hook 3 - Chapter 5 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR04c', 'Hook 4 - Chapter 6 - Alondra: Video Format 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR05c', 'Hook 5 - Chapter 11 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR06c', 'Hook 6 - Chapter 20 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR07c', 'Hook 7 - Chapter 21 - Alondra: Video Format 💥❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR08c', 'Hook 8 - Chapter 21 - Alondra: Video Format ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR09c', 'Hook 9 - Chapter 22 - Alondra: Video Format 💥❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR10c', 'Hook 10 - Chapter 24 - Alondra: Video Format ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR11c', 'Hook 11 - Chapter 25 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR12c', 'Hook 12 - Chapter 29 - Alondra: Video Format 😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR13c', 'Hook 13 - Chapter 35 - Alondra: Video Format ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR14c', 'Hook 14 - Chapter 37 - Alondra: Video Format 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR15c', 'Hook 15 - Chapter 42- Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR16c', 'Hook 16 - Chapter 42- Alondra: Video Format ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR17c', 'Hook 17 - Chapter 50 - Alondra: Video Format ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR18c', 'Hook 18 - Chapter 55 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR19c', 'Hook 19 - Chapter 56 - Alondra: Video Format 💥❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR20c', 'Hook 20 - Chapter 56 - Alondra: Video Format 💥❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR21c', 'Hook 21 - Chapter 60 - Alondra: Video Format 😭❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR22c', 'Hook 22 - Chapter 60 - Alondra: Video Format 😭❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR23c', 'Hook 23 - Chapter 80 - Alondra: Video Format 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR24c', 'Hook 24 - Chapter 81 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR25c', 'Hook 25 - Chapter 81 - Alondra: Video Format 💥❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR26c', 'Hook 26 - Chapter 83 - Alondra: Video Format 😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR27c', 'Hook 27 - Chapter 83 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR28c', 'Hook 28 - Chapter 83 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR29c', 'Hook 29 - Chapter 88 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('CR30c', 'Hook 30 - Chapter 91 - Alondra: Video Format ❤️😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS01a', 'Escena 1: Cuando tu padre te vende al mejor postor 😭', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS02a', 'Escena 2: Cuando te compran por 2 millones de euros 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS03a', 'Escena 3: Vine por lo que es mío 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS04a', 'Escena 4: Te odio, Dante de Santis ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS05a', 'Escena 5: Cuando él le aclara que ella no es una mujer cualquiera 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS06a', 'Escena 6: Cuando él reserva toda una tienda para ella 🥹❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS07a', 'Escena 7: Cuando él mata por celos... 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS08a', 'Escena 8: Cuando ella tiene que atender de emergencia a su captor... 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS09a', 'Escena 9: Cuando ella tiene su forma particular de mostrarle su cariño... ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS10a', 'Escena 10: Cuando el mafioso italiano quiere destruir tus excusas para no casarte con él... 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS11a', 'Escena 11: Cuando el mafioso italiano me da su tarjeta Amex para usarla a mi discreción 💥😆', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS12a', 'Escena 12: Cuando ella guarda un secreto... 💥 (5 slides)', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS13a', 'Escena 13: Cuando ella se entera que él la cuidaba desde hace tiempo... 😢', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS14a', 'Escena 14: Sorpresa... 🥹(11 slides)', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS15a', 'Escena 15: Cuando el mafioso macho alfa acepta comprarle ropa a sus perros 🥹', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS16a', 'Escena 16: Cuando él muestra su parte vulnerable 🥹', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS17a', 'Escena 17: Cuando él paga las consecuencias por intentar drogar a su esposa 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS18a', 'Escena 18: El cumpleaños más feliz de tu vida... ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('BPUS19a', 'Escena 19: Por favor resiste 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM01b', 'Escena 1 - Jugando con fuego 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM02b', 'Escena 2 - Tú también lo deseas 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM04b', 'Escena 4 - La tentación ya está en juego… 🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM05c', 'Escena 5 - Si te metes con fuego, al final te quemas... 🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM06c', 'Escena 6 - Pídemelo y seré todo tuyo… ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM08b', 'Escena 8 - La mentira duele más que la herida… 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM09b', 'Escena 9 - Cuando te enamoras de un mafioso… 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM10b', 'Escena 10 - En la oscuridad siempre podrás encontrar las estrellas ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM12b', 'Escena 12 - Cuando dijo que nunca me dejaría ir y me besó... ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM13b', 'Escena 13 - Todo a mi alrededor desapareció… ❤️', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM14b', 'Escena 14 - Nunca subestimes a un mafioso… 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM15b', 'Escena 15 - Apostar con un mafioso es jugársela, pero yo no me rajo… 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM16b', 'Escena 16 - Cuando el destino une dos almas en un lugar secreto, todo cambia 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('EMDUM17b', 'Escena 17 - Cuando ves la muerte de cerca, ¿quién te da fuerza para volver? 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP01c', 'Hook 1 - When you drop your purse all over the bar floor and the hot hockey player picks up your *adult* toy 💥🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP02c', 'Hook 2 - When you go to fix her smudged lipstick at the bar but she says 💥🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP03c', 'Hook 3 - When he makes you guess his name but each time you get it wrong he touches your 💥🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP04c', 'Hook 4 - When you finally guess his name right and he says 💥🌶', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP05c', 'Hook 5 - When he asks you to be his son’s nanny and tells you how much he’s willing to pay 😯💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP06c', 'Hook 6 - When you meet the boy you’re going to be nannying but he asks 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP07c', 'Hook 7 - When your boss comes home drunk and you ask him why he never called you after you hooked up 💥😢', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP08c', 'Hook 8 - When you finally ask your boss why he never called you after hooking up and he says 💥😢😯', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP10c', 'Hook 10 - When your ex best friend calls to invite you to her wedding with your ex fiance 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP11c', 'Hook 11 - When your ex best friend calls to invite you to her wedding with your ex fiance so you lie and say 💥', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME),
('TSP12c', 'Hook 12 - When your hot hockey player boss offers to be your fake boyfriend for your ex''s wedding 💥😂', 'S', 'Sistema', CURRENT_DATE, CURRENT_TIME, CURRENT_DATE, CURRENT_TIME);
